<a href="https://colab.research.google.com/github/asadbektukhtasinov/Math-2024-25-Winter/blob/main/vertopal_com_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics

Exercises 2024/2025

## 1. Basic Operations on Matrices

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1.  Calculate: $\mathbf{A}+\mathbf{B}$; $\mathbf{B}-\mathbf{A}$;
    $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2.  Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$,
    and $4\mathbf{D}$.

3.  Calculate the products $\mathbf{A}\cdot \mathbf{B}$;
    $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$;
    $\mathbf{D} \cdot \mathbf{E}$.

## 2. Determinants 2x2 and 3x3

Calculate the determinants for the 2x2 and 3x3 matrices given below.

2x2 Matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 \\
1 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
, \qquad
\mathbf{C} =
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
$$

3x3 Matrices:

$$
\mathbf{D} =
\begin{pmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
2 & 4 & -2
\end{pmatrix}
, \qquad
\mathbf{E} =
\begin{pmatrix}
3 & 1 & -1 \\
0 & 2 & 4 \\
5 & 3 & 2
\end{pmatrix}
, \qquad
\mathbf{F} =
\begin{pmatrix}
2 & -3 & 1 \\
1 & 4 & -2 \\
1 & 5 & 3
\end{pmatrix}
$$

## 3. Determinants using Laplace’s Expansion

Calculate the determinants of the following matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 1
\end{pmatrix}
,\qquad
\mathbf{B} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 0  \\
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
2 & 3 & 1 & 4 \\
1 & 0 & 0 & 6 \\
3 & 2 & 1 & 5 \\
2 & 1 & 4 & 0
\end{pmatrix}
,\qquad
\mathbf{D} =
\begin{pmatrix}
2 & 3 & 1 & 4 & 5 \\
1 & 4 & 0 & 0 & 7 \\
3 & 0 & 0 & 0 & 0 \\
2 & 1 & 4 & 3 & 2 \\
1 & 2 & 3 & 4 & 5
\end{pmatrix}
$$

## 4. Determinants from the Gauss Method and Triangular Matrices

Perform row and column operations to reduce the following matrices to an
upper triangular form and calculate their determinants by taking the
product of the diagonal elements.

$$
\mathbf{A} = \begin{pmatrix}
12 & 3 \\
-18 & -4
\end{pmatrix}\qquad\qquad
\mathbf{B} = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$

## 5. Inverse of a Matrix from the formula

1.  Find the inverse matrix for matrix

$$\mathbf{A}=\begin{pmatrix}
2 & 0 & 1 \\
0 & 1 & 0 \\
1 & 2 & 0
\end{pmatrix}$$

and verify if the result is correct.

1.  Determine the rank of the matrix:

$$\mathbf{B} =
\begin{pmatrix}
4 & -3 & 7 \\
-1 & 6 & 3 \\
2 & 9 & 1
\end{pmatrix}$$

## 6. Inverse of a Matrix using the Gauss Method

Find the inverse matrices using the Gauss method:

$$
\mathbf{A} =
\begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 1 \\
2 & 3 & 2
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{pmatrix}
$$

## 7. Linear Equations old school

Solve the following systems of equations without using matrices:

-   $3x-2y=5, \quad 2x+3y=7$,
-   $2x-3y=10, \quad 4x+5y=20$,
-   $2x - y + z = 3, \quad x + 2y - z = 1, \quad 3x - y + 2z = 11$.
-   $2x-3y+4z+2t=2, \quad 3x+2y-5z+3t=3, \quad 4x-3y+2z-5t=4, \quad 5x+4y-3z+2t=5$.

## 8. Linear equations by Cramer’s Rule

1.  Solve the system of equations:

$$\begin{cases}
   2x_1 - 3x_2 = 7\\
   3x_1 + 5x_2 = 2
\end{cases}$$

1.  Solve the system of equations:

$$\begin{cases}
   2x + y - z = 1 \\
   x - y + 2z = 4 \\
   3x - 2z = -1
\end{cases}$$

1.  Solve the system of equations:

$$\begin{cases}
   x + y + z - t = 2 \\
   x - z + 2t = 6 \\
   2x - 3y + t = 4 \\
   3x + y + 3z - 4t = -2
\end{cases}$$

1.  Why can’t the following system of equations be solved using Cramer’s
    rule?

$$\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}$$

## 9. Linear equations by Gauss Elimination

$$\begin{cases}
x + 2y - 2z = 4 \\
2x + y + z = 0 \\
3x + 2y + z = 1
\end{cases}
\quad
\begin{cases}
x + y + z - t = 2 \\
2x + y + z = 3 \\
-x + z - t = 0 \\
3x + 2y - z + 2t = -1
\end{cases}
\quad
\begin{cases}
x + y - z - t = 0 \\
2x + 3y - 2z + t = 4 \\
3x + 5z = 0 \\
-x + y - 3z + 2t = 3
\end{cases}
$$

## 10. Linear equations by Matrix Inversion

1.  Solve the system of linear equations using the inverse matrix
    method:

$$
\begin{cases}
x + 2y + 3z = 5, \\
2y + 3z = 4, \\
3z = 3.
\end{cases}
$$

1.  Solve the system of linear equations using the inverse matrix
    method:

$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 41, \\
4x_1 + 5x_2 + 6x_3 = 93, \\
7x_1 + 8x_2 + 9x_3 = 145.
\end{cases}
$$

## 11. Vectors I

1.  By what number should vector $\mathbf{a} = [3, 4]$ be multiplied so
    that its length is equal to 1?

2.  Calculate the length of vector $\mathbf{b} = [1, 1]$ and find the
    unit vector of this vector.

3.  Plot the vector and the unit vector from the previous exercise.

4.  Calculate the length of vector $\mathbf{c} = [1, 2, 3]$ and find the
    unit vector of this vector.

5.  Find the Cartesian coordinates of vector $\mathbf{v} = [2, 3, 4]$ in
    the basis
    $\{\mathbf{b_1} = [1, 0, 1], \mathbf{b_2} = [0, 1, 0], \mathbf{b_3} = [1, 0, -1]\}$.

## 12. Vectors II

1.  Perform the addition of vector $[2, 1]$ to vector $[-1, 1]$. Plot
    both vectors and their sum on a graph.

2.  Calculate the area of the triangle spanned by vectors $[2, 1, 2]$
    and $[-1, 1,1]$.

3.  Calculate the volume of the parallelepiped spanned by vectors
    $[2, 1, -1]$, $[-1, 1, 0]$, and $[1, 2, 1]$.

4.  Check if vectors $[2, 1]$ and $[-1, 1]$ are perpendicular.

5.  Calculate the angle in degrees between vectors $[4,2,1]$ and
    $[1,3,2]$.

6.  For three-dimensional vectors: $\mathbf{a}=[a_x, a_y, a_z]$,
    $\mathbf{b}=[b_x, b_y, b_z]$, $\mathbf{c}=[c_x, c_y, c_z]$, prove
    that the following identity is satisfied:

$$
\mathbf{a} \times (\mathbf{b} \times \mathbf{c}) = (\mathbf{a} \cdot \mathbf{c}) \mathbf{b} - (\mathbf{a} \cdot \mathbf{b}) \mathbf{c}.
$$

## 13. Vectors III

1.  Divide the line segment connecting points $A(-1, 2)$ and $B(3, -2)$
    in the ratio $1:3$. Illustrate the result on a graph.

2.  Project vector $\mathbf{a} = (3, 4)$ onto the $OX$ and $OY$ axes.
    Illustrate the result on a graph.

3.  Project vector $\mathbf{a} = (2,3)$ onto vector
    $\mathbf{b} = (1, 1)$. Ilustrate the result on a graph.

4.  Project vector $\mathbf{b} = (1, 1)$ onto vector
    $\mathbf{a} = (2, 3)$. Ilustrate the result on a graph.

## 14. Equations of lines on a plane

-   The line passes through points $A(1, 2)$ and $B(3, 4)$. Find the
    equation of the line.
-   The line passes through point $A(1, 2)$ and is parallel to the line
    $y = 2x + 3$. Find the equation of the line.
-   The line passes through point $A(1, 2)$ and is perpendicular to the
    line $y = 2x + 3$. Find the equation of the line.
-   We have two lines $y = 2x + 3$ and $y = 3x + 2$. Find the
    intersection point of these lines and calculate the angle between
    them.
-   Write the equation of the line passing through point $A(1, 2)$ and
    parallel to the vector $\mathbf{v} = [2, 3]$.
-   We have the line $y = 2x + 3$. Find an example of a line
    perpendicular and parallel to it.
-   We have the line $y = 2x + 3$ and point $A(1, 2)$. Find the distance
    from point $A$ to the line.
-   The line intersects the coordinate axes at points $A(2, 0)$ and
    $B(0, 3)$. Find the equation of the line.
-   Calculate the angle between the line $y = x + 3$ and the $Ox$ axis.
-   Provide a vector perpendicular to the line $x + y + 1 = 0$.

## 15. Equations of second-order curves (conic sections)

-   Find the equation of a circle with center at point $A(1,2)$ and
    radius $r=3$.
-   Find the equation of a parabola intersecting the $Ox$ axis at points
    $x=2$, $x=4$, and passing through point $y(3)=1$.
-   Find the center of the ellipse with the equation
    $x^2 + 4y^2 - 4x - 16y + 16 = 0$.
-   Find the slope ($m>0$) of the line $y=mx-5$ that is tangent to the
    circle with the equation $x^2 + y^2=1$.
-   Find the intersection points of the hyperbola $x^2 - y^2 = 1$ with
    the ellipse’s line $x^2 + 4y^2 = 6$.
-   For the given hyperbola $x^2 - y^2 = 1$, find the distance between
    its branches.

## 16. Equations of planes in space

-   The plane passes through points $A(1, 2, 3)$, $B(3, 4, 5)$, and
    $C(2, 1, 4)$. Find the equation of the plane.
-   The plane passes through point $A(1, 2, 3)$ and is parallel to the
    plane $2x + 3y + 4z = 5$. Find the equation of the plane.
-   The plane passes through point $A(1, 2, 3)$ and is perpendicular to
    the normal vector $\mathbf{n} = [2, 3, 4]$. Find the equation of the
    plane.
-   We have two planes $2x + 3y + 4z = 5$ and $3x + 4y + 2z = 6$. Find
    the line of intersection of these planes.
-   Write the equation of the plane passing through point $A(1, 2, 3)$
    and parallel to vectors $\vec{v_1} = [1, 0, 1]$ and
    $\vec{v_2} = [0, 1, -1]$.
-   We have the plane $2x + 3y + 4z = 5$. Find an example of a plane
    parallel and perpendicular to it.
-   We have the plane $2x + 3y + 4z = 5$ and point $A(1, 2, 3)$. Find
    the distance from point $A$ to this plane.
-   The plane intersects the coordinate axes at points $A(2, 0, 0)$,
    $B(0, 3, 0)$, and $C(0, 0, 4)$. Find the equation of the plane.
-   Calculate the angle between the plane $x + y + z = 1$ and the plane
    $x = 0$ (i.e., the $yz$ plane).
-   Find the vector perpendicular to the plane $x + y + z = 1$.

## 17. Equations of second-order surfaces

-   Write the equation of a sphere with center at point $P=(1,2,3)$ and
    radius $r=3$.
-   Do the spheres with equations $x^2 + y^2 + z^2 = 1$ and
    $x^2 + y^2 + z^2 = 2$ have any common points?
-   What curve in space is formed by the intersection of the sphere
    $x^2 + y^2 + z^2 = 1$ with the sphere $(x-1)^2 + y^2 + z^2 = 1$?
    Find the equation of this curve.
-   Write the equation of the tangent plane to the paraboloid
    $z=(x-1)^2+y^2+1$ at point $P(1,0,1)$.

## 18. Functions

1.  Draw in a single Geogebra notebook the following functions:
    -   $f(x) = x^2$
    -   $g(x) = \sqrt{x}$
    -   $h(x) = \frac{1}{x}$
    -   $j(x) = \sin(x)$

Find value of all the above functions at $x = 2$.

1.  Let $f(x) = 3x - 1$ and $g(x) = \sqrt{x}$. Find:
    -   $f(g(x))$
    -   $g(f(x))$
    -   $f(f(x))$
    -   $g(g(x))$

and visualize functions in a single Geogebra notebook.

1.  Let $f(x) = e^x$ and $g(x) = \ln(x)$. Check: $f(g(x))$ and
    $g(f(x))$. What do you notice?

2.  We have function $f=\{(1,7), (2,9), (3,11)\}$. Give inverse function
    $f^{-1}$.

3.  We have function $f=\{(1,7), (2,7), (3,11)\}$. Give inverse function
    $f^{-1}$.

4.  We have function $f(x)= x-1$. Give inverse function $f^{-1}$. Show
    both functions on the same Geogebra notebook.

## 19. Limits of Sequences

1.  Calculate:
    -   $\displaystyle \lim_{n \to \infty} \frac{n^2 + 3n}{2 n^2 - 2n}$

    -   $\displaystyle \lim_{n \to \infty} \frac{(2n+3)^3}{n^3-1}$
2.  Prove using the squeeze theorem:
    -   $\displaystyle\lim_{n \to \infty} \frac{\sin(n)}{n}$
3.  Find the limit of the sequence:
    -   $a_n = (1+\frac{1}{n})^n$

## 20. Limits of Real Functions

1.  Compute:

    -   $\displaystyle\lim_{x \to \infty} \frac{x^3 + 2x^2}{x^4 - 3x^3}$

2.  Find:

    -   $\displaystyle \lim_{x \to 0} \frac{\sin(3x)}{2x+1}$.

3.  Find the asymptotes of the function:

    -   $f(x) = \frac{x^2 - 1}{x^2 + 1}$
    -   $g(x) = \frac{\sin(x)}{x^2+1}$

## 21. Derivatives

1.  Compute derivatives of functions:

    -   $y(x) = -3x+3$
    -   $y(x) = \pi x + \sin(1)$
    -   $y(x) = 4+\sin(2)$
    -   $y(x) = 2x^3 - 3x^2 + 8x - 9$
    -   $y(x) = 6 x^{1/3}$
    -   $y(x) = \sqrt{x}$
    -   $y(x) = \cos(x) + \sin(x)$
    -   $y(x) = 2\sin(x) \cos(x)$
    -   $y(x) = x\sin(x)$
    -   $y(x) = (x+1)(x+1)$
    -   $y(x) = \frac{x}{x+1}$
    -   $y(x) = (x+1)\exp(x)$
    -   $y(x) = \sin(x^2)$
    -   $y(x) = \exp(-2x)$
    -   $y(x) = \frac{1}{\sin(x+1)}$
    -   $y(x) = \sqrt{2x+1}$

2.  Prove:

    -   $\frac{d}{dx} (\ln(\sin(x))) = \cot(x)$

3.  For $f(x) = \cos(x)$, verify that $f''(x) = -f(x)$.

4.  Using de l’Hospital’s Rule, find the improper limits:

    -   $\displaystyle \lim_{x\to 0} \frac{\sin{x}}{x}$

    -   $\displaystyle \lim_{x\to \infty} \frac{\ln x}{x}$

    -   $\displaystyle \lim_{x\to \infty} \frac{\exp(x)}{x}$

5.  In physics, the position of a particle is given by
    $x(t) = 3t^2 - 6t + 1$. Find the velocity $V(t)=x'(t)$ and
    acceleration $a(t)=V'(t)=x''(t)$ of the particle at time $t = 2$.

## 22. Extremum

1.  The profit function is $P(u) = -2u^2 + 50u - 300$, where $u$ is the
    number of units sold. Find the number of units that maximize profit.

2.  You have 10 meters of string, and you need to use it to enclose the
    largest possible rectangular. Find the dimensions of the rectangle.

3.  Find extremum od $f(x) = x^2 + 3x - 5$.

4.  Find extremum of $f(x) =\frac{x^2+2x+1}{x-1}$.

## 23. Taylor Series

1.  Find the Taylor series and visualize obtained functions in Geogebra:
    -   $f(x) = \cos(x)$ around $x = 0$ up to the 4th degree.
    -   $h(x) = 1/(1-x)$ around $x = 0$ up to the 4rd degree.
    -   $g(x) = \sin(x)$ around $x = \pi$ up to the 4rd degree.
2.  Find a tangent line $y = f'(x_0) (x-x_0) + f(x_0)$ to the function
    $f(x) = e^{\sin(x)}$ at $x_0 = \pi$. Hints for Geogebra
    visualization: define f(x), include slider s, define y = f’(s)
    (x-s) + f(s), and include point P(s, f(s)).

## 24. Integrals

1.  Compute:

    -   $\int 1 dx$
    -   $\int (x^2 +2) dx$
    -   $\int 2\sin(x) dx$
    -   $\int \frac{3}{x} dx$
    -   $\int \frac{1}{x^2} dx$
    -   $\int \left( \frac{1}{3}x^4 - 5 \right) \, dx$
    -   $\int (\sin^2 x + \cos^2 x) \, dx$
    -   $\int (5 \sin x + 3e^x) \, dx$
    -   $\int \sqrt[3]{x} \, dx$
    -   $\int \sqrt{10x} \, dx$
    -   $\int \cos\left(\frac{5}{2}x + 3\right) \, dx$
    -   $\int \frac{\cos(\ln(x))}{x} \, dx$
    -   $\int x \ln(x) \, dx$
    -   $\int x e^x \, dx$

2.  Calculate integrals over the interval $[0, \pi]$ and visualize them
    in Geogebra:

    -   $f(x)=2x+1$
    -   $g(x)=x^2$

3.  Calculate the area of the region bounded by the lines: $x = 1$,
    $x = 2$, $y = 0$, and $y = x^2 + 1$. Show it in Geogebra.

4.  Calculate the area under the sine curve over the interval
    $[0, \pi]$, using:

$$P = \int_a^b f(x) \, dx = \int_0^\pi \sin(x) \, dx$$

1.  Calculate the length of the sine curve over the same interval using:

$$L = \int_a^b \sqrt{1 + (f'(x))^2} \, dx= \int_0^\pi \sqrt{1 + \cos^2(x)} \, dx
$$

1.  Find the distance of the moving particle between time $t=0$ and
    $t=2$ for the following position function: $x(t) = 3t^2 - 6t + 1$.

## 25. Differential Equations

1.  Solve the following first-order ordinary differential equations:

    -   $y'(x)= y$
    -   $y'(x) = \frac{1}{2y(x)}$

2.  Solve the first-order ordinary differential equations using the
    method of separation of variables for $x$ and $y=y(x)$:

    -   $\frac{dy}{dx} = \frac{x}{y}$
    -   $\frac{dy}{dx} = \frac{y}{x}$
    -   $\frac{dy}{dx} = xy$

3.  Solve the second-order ordinary differential equations:

    -   $y''(x) + y'(x) = 0$, with boundary conditions $y(0) = 2$ and
        $y'(0) = -1$

    -   $y''(x) - y(x)= 0$, with boundary conditions $y(0) = 2$ and
        $y'(0) = 0$

    -   $\frac{d^2\,y(x)}{dx^2} = -\omega^2 y(x)$.

4.  Check if the function $\psi(t, x) = A \cos(\omega t + kx)$ is a
    solution of the second-order partial differential equation (the
    so-called “wave equation”), where
    $v = \frac{\omega}{k} = \frac{2\pi / T}{2\pi / \lambda}$:

$$
\frac{\partial^2 \psi(t, x)}{\partial t^2} - v^2 \frac{\partial^2 \psi(t, x)}{\partial x^2} = 0.
$$

In [ ]:
               # TASK 4 QUESTIONS
       import numpy as np

# Define matrix A
A = np.array([[12, 3], [-18, -4]], dtype=float)

def solve_matrix_A(matrix):
    print("Initial Matrix A:")
    print(matrix)

    # Step 1:
    factor = matrix[1, 0] / matrix[0, 0]
    matrix[1, :] -= factor * matrix[0, :]

    print("\nMatrix A after row operation:")
    print(matrix)

    # Step 2: Calculate determinant
    determinant = np.prod(np.diag(matrix))
    print(f"\nDeterminant of Matrix A: {determinant}")

# Solve for Matrix A
solve_matrix_A(A.copy())


Initial Matrix A:
[[ 12.   3.]
 [-18.  -4.]]

Matrix A after row operation:
[[12.   3. ]
 [ 0.   0.5]]

Determinant of Matrix A: 6.0


In [ ]:
# Define matrix B
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)

def solve_matrix_B(matrix):
    print("Initial Matrix B:")
    print(matrix)

    rows, cols = matrix.shape
    for i in range(min(rows, cols)):
        for j in range(i + 1, rows):
            if matrix[j, i] != 0:
                factor = matrix[j, i] / matrix[i, i]
                matrix[j, i:] -= factor * matrix[i, i:]
    print("\nMatrix B after row operations (Upper Triangular):")
    print(matrix)
    # Step 2: Calculate determinant
    determinant = np.prod(np.diag(matrix))
    print(f"\nDeterminant of Matrix B: {determinant}")

# Solve for Matrix B
solve_matrix_B(B.copy())


Initial Matrix B:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Matrix B after row operations (Upper Triangular):
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]

Determinant of Matrix B: -0.0


In [ ]:
     # TASK 5 QUESTIONS
     import numpy as np

# Define Matrix A
A = np.array([[2, 0, 1], [0, 1, 0], [1, 2, 0]])

# Step 1: Calculate the inverse of A
try:
    A_inv = np.linalg.inv(A)
    print("Inverse of Matrix A:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("Matrix A is not invertible.")

# Step 2: Verify the result
if 'A_inv' in locals():  # Check if the inverse was computed
    identity_check = np.dot(A, A_inv)
    print("\nA * A^(-1) (Should be Identity Matrix):")
    print(identity_check)


Inverse of Matrix A:
[[ 0. -2.  1.]
 [ 0.  1.  0.]
 [ 1.  4. -2.]]

A * A^(-1) (Should be Identity Matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Define Matrix B
B = np.array([[4, -3, 7], [-1, 6, 3], [2, 9, 1]])

# Step 1: Calculate the rank of Matrix B
rank_B = np.linalg.matrix_rank(B)
print("Rank of Matrix B:", rank_B)

Rank of Matrix B: 3
